# Generated by Django 4.1.3 on 2023-02-23 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_applied_mechanics_basic_electronic_engineering_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='physics',
            old_name='name',
            new_name='name1',
        ),
        migrations.RenameField(
            model_name='physics',
            old_name='owner',
            new_name='owner1',
        ),
        migrations.RenameField(
            model_name='physics',
            old_name='pdf',
            new_name='pdf1',
        ),
    ]
