# Generated by Django 4.1.3 on 2023-02-23 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_name_physics_name1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='physics',
            old_name='name1',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='physics',
            old_name='owner1',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='physics',
            old_name='pdf1',
            new_name='pdf',
        ),
    ]
