# Generated by Django 4.1.3 on 2023-02-28 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_name1_physics_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload_Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=100)),
                ('faculty', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to='store/pdf/')),
            ],
        ),
        migrations.AlterField(
            model_name='applied_mechanics',
            name='pdf',
            field=models.FileField(upload_to='store/pdfs/Applied_Mechanics'),
        ),
    ]
