# Generated by Django 4.1.3 on 2023-02-28 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_upload_subjects_alter_applied_mechanics_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_id', models.IntegerField(max_length=10)),
                ('faculty', models.CharField(max_length=100)),
            ],
        ),
    ]
