# Generated by Django 4.1.3 on 2023-02-28 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_faculties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculties',
            name='faculty_id',
            field=models.IntegerField(),
        ),
    ]
