# Generated by Django 4.1.3 on 2023-03-04 04:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_faculties_faculty_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.faculty')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.semester')),
            ],
        ),
        migrations.DeleteModel(
            name='Basic_Electronic_Engineering',
        ),
        migrations.DeleteModel(
            name='Computer_Programming',
        ),
        migrations.DeleteModel(
            name='Digital_Logic',
        ),
        migrations.DeleteModel(
            name='Electric_Circuit_Theory',
        ),
        migrations.DeleteModel(
            name='Faculties',
        ),
        migrations.DeleteModel(
            name='Math1',
        ),
        migrations.DeleteModel(
            name='Math2',
        ),
        migrations.DeleteModel(
            name='Math3',
        ),
        migrations.AddField(
            model_name='upload_subjects',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='upload_subjects',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.faculty'),
        ),
        migrations.AlterField(
            model_name='upload_subjects',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.semester'),
        ),
        migrations.AlterField(
            model_name='upload_subjects',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.subject'),
        ),
    ]
