# Generated by Django 4.1.3 on 2023-03-04 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_file_upload_subjects_downvotes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='semester',
        ),
        migrations.CreateModel(
            name='SubjectSemester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.subject')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectFaculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.faculty')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.subject')),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='faculties',
            field=models.ManyToManyField(through='myapp.SubjectFaculty', to='myapp.faculty'),
        ),
        migrations.AddField(
            model_name='subject',
            name='semesters',
            field=models.ManyToManyField(through='myapp.SubjectSemester', to='myapp.semester'),
        ),
    ]
