# Generated by Django 4.1.3 on 2023-03-06 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_rename_faculty_upload_subjects_faculties'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectfaculty',
            name='semester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.semester'),
        ),
        migrations.AddField(
            model_name='subjectsemester',
            name='faculty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.faculty'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='subjectfaculty',
            unique_together={('subject', 'faculty', 'semester')},
        ),
        migrations.AlterUniqueTogether(
            name='subjectsemester',
            unique_together={('subject', 'semester', 'faculty')},
        ),
    ]
