# Generated by Django 4.1.3 on 2023-03-06 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_subjectfaculty_semester_subjectsemester_faculty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectsemester',
            name='faculty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.faculty'),
        ),
    ]
